#!/usr/bin/env bash
# You must use the while loop (for and until are forbidden)
# You must use the if statement

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
