#!/usr/bin/env bash
# You must use the for loop (while and until are forbidden)
#   Only displays the part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
